name: parking_reminder
description: "Parking Reminder."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.7.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.27.2
  firebase_messaging: ^14.7.20
  firebase_remote_config: ^4.3.19
  cloud_firestore: ^4.15.9
  geolocator: ^12.0.0
  latlong2: ^0.9.1
  shared_preferences: ^2.5.3
  url_launcher: ^6.3.1
  flutter_background_service: ^5.1.0
  flutter_local_notifications: ^19.1.0
  cupertino_icons: ^1.0.8
  external_app_launcher: ^4.0.3
  simple_kalman: ^1.0.2
  google_mobile_ads: ^6.0.0
  rxdart: ^0.28.0
  flutter_background_service_android: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/background_image.jpg
    - assets/app_logo.png

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/ic_custom.png"
  android_icon_name: "ic_custom"