name: parking_reminder
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.7.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.32.0
  firebase_messaging: ^14.9.4
  firebase_remote_config: ^4.4.7
  cloud_firestore: ^4.17.5
  geolocator: ^12.0.0
  latlong2: ^0.9.1
  shared_preferences: ^2.5.3
  flutter_local_notifications: ^19.1.0
  url_launcher: ^6.2.5
  android_intent_plus: ^4.0.3
  flutter_background_service: ^5.1.0
  rxdart: ^0.27.7
  flutter_background_service_android: ^6.3.0
  external_app_launcher: ^4.0.3
  google_maps_flutter: ^2.5.3
  google_maps_flutter_web: ^0.5.4+4
  google_places_flutter: ^2.0.8
  http: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2

flutter:
  uses-material-design: true
  assets:
    - assets/security-agent.png
    - assets/food.png
    - assets/cart.png
    - assets/garage.png
    - assets/tires.png
    - assets/pharmacy.png
    - assets/gasstation.png

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/ic_custom.png"
  android_icon_name: "ic_custom"